packages:
  - apps/*
  - packages/*
  - scripts/*
catalog:
  zod: ^3.25.71
  better-auth: ^1.2.12
  autumn-js: ^0.0.77
  superjson: ^2.2.2
  '@trpc/server': ^11.4.3
  '@trpc/client': ^11.4.3
  '@trpc/tanstack-react-query': ^11.4.3
  wrangler: ^4.23.0
  typescript: ^5.8.3
  drizzle-orm: ^0.44.2
  drizzle-kit: ^0.31.4
  '@types/node': ^24.0.10
  'react': ^19.1.0
  'react-dom': ^19.1.0
onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
patchedDependencies:
  novel: patches/novel.patch
