packages:
  - apps/*
  - packages/*
  - scripts/*
catalog:
  zod: ^4.1.1
  better-auth: ^1.3.7
  autumn-js: ^0.1.20
  superjson: ^2.2.2
  '@trpc/server': ^11.5.0
  '@trpc/client': ^11.5.0
  '@trpc/tanstack-react-query': ^11.5.0
  wrangler: ^4.32.0
  typescript: ^5.9.2
  drizzle-orm: ^0.44.5
  drizzle-kit: ^0.31.4
  '@types/node': ^24.3.0
  'react': ^19.1.1
  'react-dom': ^19.1.1
onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
patchedDependencies:
  novel: patches/novel.patch
