packages:
  - apps/*
  - packages/*
  - scripts/*
catalog:
  zod: ^4.0.14
  better-auth: ^1.3.4
  autumn-js: ^0.1.1
  superjson: ^2.2.2
  '@trpc/server': ^11.4.4
  '@trpc/client': ^11.4.4
  '@trpc/tanstack-react-query': ^11.4.4
  wrangler: ^4.27.0
  typescript: ^5.9.2
  drizzle-orm: ^0.44.4
  drizzle-kit: ^0.31.4
  '@types/node': ^24.2.0
  'react': ^19.1.1
  'react-dom': ^19.1.1
onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
patchedDependencies:
  novel: patches/novel.patch
